version: 2
updates:

  - package-ecosystem: "nuget"
    target-branch: "master"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"

    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
        versions: [ ">=4.13.0" ]
