name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CONDITION }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUNS_ON }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUN_SCRIPT }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
  DISPOSABLEHELPERSTEST:
    name: Test - disposable_helpers (DisposableHelpersTest)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CHECKOUT_SUBMODULES }}
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_RUN_SCRIPT }} PipelineRunEntry --args "run=test;idsToRun=DisposableHelpersTest"
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSTEST_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  DISPOSABLEHELPERSBUILD:
    name: Build - disposable_helpers (DisposableHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CHECKOUT_SUBMODULES }}
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_RUN_SCRIPT }} PipelineRunEntry --args "run=build;idsToRun=DisposableHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: disposable_helpers___DISPOSABLEHELPERSBUILD
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - DISPOSABLEHELPERSTEST
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSBUILD_CONDITION == 'true' && needs.DISPOSABLEHELPERSTEST.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  DISPOSABLEHELPERSPUBLISH:
    name: Publish - disposable_helpers (DisposableHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
        pattern: disposable_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_RUN_SCRIPT }} PipelineRunEntry --args "run=publish;idsToRun=DisposableHelpersPublish"
    needs:
    - PRE_SETUP
    - DISPOSABLEHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_DISPOSABLEHELPERSPUBLISH_CONDITION == 'true' && needs.DISPOSABLEHELPERSTEST.result != 'failure' && needs.DISPOSABLEHELPERSBUILD.result != 'failure'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - DISPOSABLEHELPERSTEST
    - DISPOSABLEHELPERSBUILD
    - DISPOSABLEHELPERSPUBLISH
    if: success() || failure() || always()
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_DISPOSABLEHELPERSTEST: ${{ needs.DISPOSABLEHELPERSTEST.result }}
      NUKE_RUN_RESULT_GITHUB_DISPOSABLEHELPERSBUILD: ${{ needs.DISPOSABLEHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_DISPOSABLEHELPERSPUBLISH: ${{ needs.DISPOSABLEHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
